### ISSUE TITLE
3.6有方法装Crypto吗

### ISSUE THREAD

**Issue by harry7988** [tychxn/jd-login#2]
python3.6有方法装Crypto吗？

**Comment by tychxn** [comment]
要安装肯定是可以的，我搜索了一下，可以参考：[链接1](https://blog.csdn.net/a624806998/article/details/78596543)  [链接2](https://www.jianshu.com/p/a73fd1af5e99)  [链接3](https://stackoverflow.com/questions/41843266/microsoft-windows-python-3-6-pycrypto-installation-error)
其中麻烦在于：

1. 要安装庞大的VS.
2. 需要解决一些报错问题.

我比较懒，用了Python3.5，因为有轮子……

**Comment by harry7988** [comment]
感谢

**Comment by tychxn** [comment]
不客气~
